support ddns and add some retry configs

diff --git a/files/root/etc/init.d/udp2raw b/files/root/etc/init.d/udp2raw
--- a/files/root/etc/init.d/udp2raw
+++ b/files/root/etc/init.d/udp2raw
@@ -4,6 +4,8 @@ START=88
 STOP=15
 USE_PROCD=1
 
+EXTRA_COMMANDS="check_domain check_domain_loop"
+
 NAME=udp2raw
 
 _log() {
@@ -45,6 +47,73 @@ export_ipt_rules() {
 	$(iptables-save -t filter | grep -E "${NAME}DwrW|^\*|^COMMIT" | sed 's/^-A /-I /')
 	EOF
 CAT
+}
+
+check_domain_for_server() {
+	local server="$1"
+
+	if [ -z "$server" -o "$server" == "nil" ]; then
+		return 1
+	elif ! validate_server_section "$server"; then
+		_log "err" "Server config validation failed."
+		return 1
+	fi
+
+	local config_file="/var/etc/${NAME}.${server}.conf"
+	if ! [ -f "$config_file" ]; then
+		return 1
+	fi
+	/sbin/validate_data "ipaddr" "$server_addr" >/dev/null 2>&1
+	if [ $? -eq 0 ]; then
+		return 1
+	fi  
+	server_addr=$(nslookup "$server_addr" | \
+		sed -n 's/^Address[[:space:]]*[0-9]*:[[:space:]]*\(\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\)$/\1/p')
+	if [ -z "$server_addr" ]; then
+		_log "err" "Server address validation failed."
+		return 1
+	fi
+	old_ip=$(sed -n 's/^-r \([0-9.]\+\):.*/\1/p' $config_file)
+	if [ "$old_ip" = "$server_addr" ]; then
+		return 1
+	fi
+	_log "info" ""$server" server address changed from $old_ip to $server_addr"
+	create_config "$config_file" || return 1
+	return 0
+}
+
+check_domain() {
+	if ! validate_config_section "general" ; then
+		_log "err" "Config validate failed."
+		return 1
+	fi
+	should_reload=0
+	for srv in $server; do
+		if check_domain_for_server $srv; then
+			should_reload=1
+		fi
+	done
+	if [ $should_reload -eq 1 ]; then
+		_log "info" "reloading udp2raw service"
+		reload
+	fi
+}
+
+check_domain_loop(){
+	while true; do
+		check_domain
+		sleep 60
+	done
+}
+
+start_check_domain_loop() {
+	procd_open_instance
+	procd_set_param command /usr/bin/udp2raw_check_domain_loop
+	procd_set_param respawn
+	procd_set_param pidfile "/var/run/${NAME}.check_domain_loop.pid"
+	procd_set_param stdout 1
+	procd_set_param stderr 1
+	procd_close_instance
 }
 
 create_config() {
@@ -92,6 +161,9 @@ validate_server_section() {
 		'auto_rule:bool:1' \
 		'keep_rule:bool:0' \
 		'seq_mode:range(0,4)' \
+		'respawn_threshold:range(1,3600):600' \
+		'respawn_timeout:range(1,3600):60' \
+		'respawn_retry:range(1,1000):120' \
 		'lower_level:string' \
 		'source_ip:ipaddr' \
 		'source_port:port' \
@@ -127,10 +199,13 @@ start_instance() {
 	procd_open_instance
 	procd_set_param command /usr/bin/udp2raw
 	procd_append_param command --conf-file "$config_file"
-	procd_set_param respawn
+	procd_set_param respawn ${respawn_threshold} ${respawn_timeout} ${respawn_retry}
+	_log "info" "respawn with: ${respawn_threshold} ${respawn_timeout} ${respawn_retry} ${config_file}"
 	procd_set_param file "$config_file"
 	[ -n "$daemon_user" ] && procd_set_param user "$daemon_user" && _log "info" "running from ${daemon_user} user"
 	procd_set_param pidfile "/var/run/${NAME}.${server}.pid"
+	# procd_set_param stdout 1
+	# procd_set_param stderr 1
 	procd_close_instance
 }
 
@@ -149,6 +224,7 @@ start_service() {
 		start_instance $srv
 	done
 	export_ipt_rules
+	start_check_domain_loop
 }
 
 stop_service() {
